/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Float64,
});
export const ExerciseSession = IDL.Record({
  'date' : IDL.Int,
  'exercises' : IDL.Vec(Exercise),
});
export const WorkoutDay = IDL.Record({
  'day' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const WorkoutPlan = IDL.Record({
  'fitnessLevel' : IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  }),
  'days' : IDL.Vec(WorkoutDay),
  'goal' : IDL.Variant({
    'get_fit' : IDL.Null,
    'lose_weight' : IDL.Null,
    'build_muscle' : IDL.Null,
  }),
  'name' : IDL.Text,
});
export const AIResponse = IDL.Record({
  'recommendedPlan' : IDL.Opt(WorkoutPlan),
  'message' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'fitnessLevel' : IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  }),
  'heightCm' : IDL.Float64,
  'goal' : IDL.Variant({
    'get_fit' : IDL.Null,
    'lose_weight' : IDL.Null,
    'build_muscle' : IDL.Null,
  }),
  'weightKg' : IDL.Float64,
});
export const CustomWorkoutPlan = IDL.Record({
  'id' : IDL.Text,
  'days' : IDL.Vec(WorkoutDay),
  'name' : IDL.Text,
});
export const ProgressPhoto = IDL.Record({
  'blob' : ExternalBlob,
  'date' : IDL.Int,
  'note' : IDL.Opt(IDL.Text),
});
export const WeightEntry = IDL.Record({
  'date' : IDL.Int,
  'weightKg' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProgressPhoto' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [], []),
  'addSession' : IDL.Func([ExerciseSession], [], []),
  'addWeightEntry' : IDL.Func([IDL.Float64], [], []),
  'askAI' : IDL.Func([IDL.Text], [AIResponse], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomPlan' : IDL.Func([IDL.Text], [], []),
  'getAllPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomPlans' : IDL.Func([], [IDL.Vec(CustomWorkoutPlan)], ['query']),
  'getProgressPhotos' : IDL.Func([], [IDL.Vec(ProgressPhoto)], ['query']),
  'getRecommendedPlan' : IDL.Func([], [IDL.Opt(WorkoutPlan)], []),
  'getSessions' : IDL.Func([], [IDL.Vec(ExerciseSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'initializeWorkoutPlans' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomPlan' : IDL.Func([CustomWorkoutPlan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Float64,
  });
  const ExerciseSession = IDL.Record({
    'date' : IDL.Int,
    'exercises' : IDL.Vec(Exercise),
  });
  const WorkoutDay = IDL.Record({
    'day' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const WorkoutPlan = IDL.Record({
    'fitnessLevel' : IDL.Variant({
      'intermediate' : IDL.Null,
      'beginner' : IDL.Null,
      'advanced' : IDL.Null,
    }),
    'days' : IDL.Vec(WorkoutDay),
    'goal' : IDL.Variant({
      'get_fit' : IDL.Null,
      'lose_weight' : IDL.Null,
      'build_muscle' : IDL.Null,
    }),
    'name' : IDL.Text,
  });
  const AIResponse = IDL.Record({
    'recommendedPlan' : IDL.Opt(WorkoutPlan),
    'message' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'fitnessLevel' : IDL.Variant({
      'intermediate' : IDL.Null,
      'beginner' : IDL.Null,
      'advanced' : IDL.Null,
    }),
    'heightCm' : IDL.Float64,
    'goal' : IDL.Variant({
      'get_fit' : IDL.Null,
      'lose_weight' : IDL.Null,
      'build_muscle' : IDL.Null,
    }),
    'weightKg' : IDL.Float64,
  });
  const CustomWorkoutPlan = IDL.Record({
    'id' : IDL.Text,
    'days' : IDL.Vec(WorkoutDay),
    'name' : IDL.Text,
  });
  const ProgressPhoto = IDL.Record({
    'blob' : ExternalBlob,
    'date' : IDL.Int,
    'note' : IDL.Opt(IDL.Text),
  });
  const WeightEntry = IDL.Record({
    'date' : IDL.Int,
    'weightKg' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProgressPhoto' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [], []),
    'addSession' : IDL.Func([ExerciseSession], [], []),
    'addWeightEntry' : IDL.Func([IDL.Float64], [], []),
    'askAI' : IDL.Func([IDL.Text], [AIResponse], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomPlan' : IDL.Func([IDL.Text], [], []),
    'getAllPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomPlans' : IDL.Func([], [IDL.Vec(CustomWorkoutPlan)], ['query']),
    'getProgressPhotos' : IDL.Func([], [IDL.Vec(ProgressPhoto)], ['query']),
    'getRecommendedPlan' : IDL.Func([], [IDL.Opt(WorkoutPlan)], []),
    'getSessions' : IDL.Func([], [IDL.Vec(ExerciseSession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'initializeWorkoutPlans' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomPlan' : IDL.Func([CustomWorkoutPlan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };