/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIResponse {
  'recommendedPlan' : [] | [WorkoutPlan],
  'message' : string,
}
export interface CustomWorkoutPlan {
  'id' : string,
  'days' : Array<WorkoutDay>,
  'name' : string,
}
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : number,
}
export interface ExerciseSession {
  'date' : bigint,
  'exercises' : Array<Exercise>,
}
export type ExternalBlob = Uint8Array;
export interface ProgressPhoto {
  'blob' : ExternalBlob,
  'date' : bigint,
  'note' : [] | [string],
}
export interface UserProfile {
  'age' : bigint,
  'fitnessLevel' : { 'intermediate' : null } |
    { 'beginner' : null } |
    { 'advanced' : null },
  'heightCm' : number,
  'goal' : { 'get_fit' : null } |
    { 'lose_weight' : null } |
    { 'build_muscle' : null },
  'weightKg' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'date' : bigint, 'weightKg' : number }
export interface WorkoutDay { 'day' : string, 'exercises' : Array<Exercise> }
export interface WorkoutPlan {
  'fitnessLevel' : { 'intermediate' : null } |
    { 'beginner' : null } |
    { 'advanced' : null },
  'days' : Array<WorkoutDay>,
  'goal' : { 'get_fit' : null } |
    { 'lose_weight' : null } |
    { 'build_muscle' : null },
  'name' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProgressPhoto' : ActorMethod<[ExternalBlob, [] | [string]], undefined>,
  'addSession' : ActorMethod<[ExerciseSession], undefined>,
  'addWeightEntry' : ActorMethod<[number], undefined>,
  'askAI' : ActorMethod<[string], AIResponse>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCustomPlan' : ActorMethod<[string], undefined>,
  'getAllPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomPlans' : ActorMethod<[], Array<CustomWorkoutPlan>>,
  'getProgressPhotos' : ActorMethod<[], Array<ProgressPhoto>>,
  'getRecommendedPlan' : ActorMethod<[], [] | [WorkoutPlan]>,
  'getSessions' : ActorMethod<[], Array<ExerciseSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightHistory' : ActorMethod<[], Array<WeightEntry>>,
  'initializeWorkoutPlans' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCustomPlan' : ActorMethod<[CustomWorkoutPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];